basePath: /api/v1
definitions:
  github_com_georgifotev1_nuvelaone-api_internal_domain.CreateUserRequest:
    properties:
      email:
        type: string
      password:
        minLength: 8
        type: string
    required:
    - email
    - password
    type: object
  github_com_georgifotev1_nuvelaone-api_internal_domain.UpdateUserRequest:
    properties:
      email:
        type: string
    type: object
  github_com_georgifotev1_nuvelaone-api_internal_domain.User:
    properties:
      created_at:
        type: string
      email:
        type: string
      id:
        type: integer
      updated_at:
        type: string
    type: object
host: localhost:8080
info:
  contact: {}
  description: REST API for NuvelaOne application
  title: NuvelaOne API
  version: 1.0.0
paths:
  /users:
    get:
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/github_com_georgifotev1_nuvelaone-api_internal_domain.User'
            type: array
      summary: List all users
      tags:
      - users
    post:
      consumes:
      - application/json
      parameters:
      - description: User payload
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/github_com_georgifotev1_nuvelaone-api_internal_domain.CreateUserRequest'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/github_com_georgifotev1_nuvelaone-api_internal_domain.User'
      summary: Create a user
      tags:
      - users
  /users/{id}:
    delete:
      parameters:
      - description: User ID
        in: path
        name: id
        required: true
        type: integer
      responses:
        "204":
          description: No Content
      summary: Delete a user
      tags:
      - users
    get:
      parameters:
      - description: User ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/github_com_georgifotev1_nuvelaone-api_internal_domain.User'
      summary: Get user by ID
      tags:
      - users
    put:
      consumes:
      - application/json
      parameters:
      - description: User ID
        in: path
        name: id
        required: true
        type: integer
      - description: Update payload
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/github_com_georgifotev1_nuvelaone-api_internal_domain.UpdateUserRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/github_com_georgifotev1_nuvelaone-api_internal_domain.User'
      summary: Update a user
      tags:
      - users
swagger: "2.0"
